version: '3.8'

services:
  web:
    build: .
    ports:
      - "8501:8501"
    environment:
      - MOCK_API_URL=http://api:8081
    depends_on:
      - api
    volumes:
      - .:/app

  api:
    build: .
    command: python src/mock_services.py
    ports:
      - "8081:8081"
    volumes:
      - .:/app
